version: "3.9"
name: meupetminhavida

services:
  back-end:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.nest.dev
    ports:
      - 3000:3000
    volumes:
      - ../.:/home/node/app
    networks:
      - inner-network
    env_file:
      - ../.env
    depends_on:
      dev-db-mysql:
        condition: service_healthy

  dev-db-mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meupetminhavidadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inner-network

networks:
  inner-network:

volumes:
  db-data:
