name: Sync Dev with Main

on:
  push:
    branches:
      - main
      
permissions:
  actions: write
  contents: write
  deployments: write
  packages: write

jobs:
  sync-dev-with-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Recreate Dev branch
        run: |
          git pull
          git checkout main
          git checkout -b dev
          git push origin dev -f
