name: Sync Dev with Main

on:
  push:
    branches:
      - main

jobs:
  sync-dev-with-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Recreate Dev branch
        run: |
          git branch -D dev
          git checkout -b dev
          git push origin dev -f
