name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: yarn install
      - run: yarn test:unit-ci
